spring.application.name=KnowledgeAssistant
server.address=127.0.0.1

spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.model=gpt-4.1-mini-2025-04-14
spring.ai.openai.chat.max-tokens=200
spring.ai.openai.timeout=30s
spring.ai.openai.max-retries=0

spring.datasource.url=jdbc:postgresql://127.0.01:5433/knowledge
spring.datasource.username=knowledge
spring.datasource.password=${KNOWLEDGE_DB_PASSWORD}

spring.ai.openai.embedding.model=text-embedding-3-small
spring.ai.openai.embedding.dimensions=1536

spring.ai.vectorstore.pgvector.dimensions=1536
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.index-type=NONE

